### ISSUE TITLE
Failed to run webpack-example

### ISSUE THREAD

**Issue by denny-z** [noppa/ng-hot-reload#10]
Steps to reproduce:
1. Clone the project
2. Go to `packages/demo`
3. Run `npm install`
4. Run `yarn webpack-example`

![screenshot from 2018-10-07 15-30-55](https://user-images.githubusercontent.com/17167471/46581734-44777100-ca46-11e8-8580-7261f7c6e1e8.png)

**Comment by noppa** [comment]
Yeah, sorry about that. The repo uses [lerna](https://github.com/lerna/lerna) to manage dependencies between the packages and it's admittedly bit of a mess. The actual commands you need are

Installation (run these in the *root* directory):
```sh
yarn
yarn run lerna bootstrap
yarn run lerna run build
```
These commands should link & build the subpackages correctly.

After that, you can go to `packages/demo` and run `yarn webpack-example`.

Let me know if that works for you and I'll update the readme with better instructions.
