### ISSUE TITLE
ngAnimate doesn't work correctly when hot-reload is active

### ISSUE THREAD

**Issue by YonathanB** [noppa/ng-hot-reload#14]
Maybe is due to a bad config on my side but when I use the `ng-hot-reload-loader`, ngAnimate doesn't work. The ng-enter and ng-leave class aren't added.

Do you have any idea why behavior is broken?

**Comment by noppa** [comment]
I haven't actually tried using this with ngAnimate yet, so I don't have any idea, really.  
I'll take a look as soon as I've got some time, which might be a week or two from now, I'm afraid.

**Comment by noppa** [comment]
Should be fixed in version 2.1.0.
