### ISSUE TITLE
make plugin play nice with typescript 

### ISSUE THREAD

**Issue by nbaleli-w** [noppa/ng-hot-reload#19]
currently this plugin's loader comes after the typescript one, resulting in sourcemaps not working properly, and having to debug es3 code -/

any tips on how to make it play nicely together ?

**Comment by noppa** [comment]
@nbaleli-w This should be now fixed in vesion 3.

**Comment by nbaleli-w** [comment]
@noppa 
I can confirm it's indeed working, thank you very much for your time !
